/** Generated by npm run build — 2026-06-09T09:09:25.537Z */
window.SEASON_RUSH_ADS = {
  "enabled": true,
  "publisherId": "ca-pub-4190145625443935",
  "slots": {
    "leaderboard": "0000000000",
    "incontent": "0000000001",
    "rectangle": "0000000002",
    "footer": "0000000003"
  },
  "autoAds": true,
  "consentRequired": true
};
